import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PaisesService {

  countryData =  [
    {"name":"Afghanistan","code":"93","iso":"AF","id":1},
    {"name":"Albania","code":"355","iso":"AL","id":2},
    {"name":"Algeria","code":"213","iso":"DZ","id":3},
    {"name":"American Samoa","code":"1-684","iso":"AS","id":4},
    {"name":"Andorra","code":"376","iso":"AD","id":5},
    {"name":"Angola","code":"244","iso":"AO","id":6},
    {"name":"Anguilla","code":"1-264","iso":"AI","id":7},
    {"name":"Antarctica","code":"672","iso":"AQ","id":8},
    {"name":"Antigua and Barbuda","code":"1-268","iso":"AG","id":9},
    {"name":"Argentina","code":"54","iso":"AR","id":10},
    {"name":"Armenia","code":"374","iso":"AM","id":11},
    {"name":"Aruba","code":"297","iso":"AW","id":12},
    {"name":"Australia","code":"61","iso":"AU","id":13},
    {"name":"Austria","code":"43","iso":"AT","id":14},
    {"name":"Azerbaijan","code":"994","iso":"AZ","id":15},
    {"name":"Bahamas","code":"1-242","iso":"BS","id":16},
    {"name":"Bahrain","code":"973","iso":"BH","id":17},
    {"name":"Bangladesh","code":"880","iso":"BD","id":18},
    {"name":"Barbados","code":"1-246","iso":"BB","id":19},
    {"name":"Belarus","code":"375","iso":"BY","id":20},
    {"name":"Belgium","code":"32","iso":"BE","id":21},
    {"name":"Belize","code":"501","iso":"BZ","id":22},
    {"name":"Benin","code":"229","iso":"BJ","id":23},
    {"name":"Bermuda","code":"1-441","iso":"BM","id":24},
    {"name":"Bhutan","code":"975","iso":"BT","id":25},
    {"name":"Bolivia","code":"591","iso":"BO","id":26},
    {"name":"Bosnia and Herzegovina","code":"387","iso":"BA","id":27},
    {"name":"Botswana","code":"267","iso":"BW","id":28},
    {"name":"Brazil","code":"55","iso":"BR","id":29},
    {"name":"British Indian Ocean Territory","code":"246","iso":"IO","id":30},
    {"name":"British Virgin Islands","code":"1-284","iso":"VG","id":31},
    {"name":"Brunei","code":"673","iso":"BN","id":32},
    {"name":"Bulgaria","code":"359","iso":"BG","id":33},
    {"name":"Burkina Faso","code":"226","iso":"BF","id":34},
    {"name":"Burundi","code":"257","iso":"BI","id":35},
    {"name":"Cambodia","code":"855","iso":"KH","id":36},
    {"name":"Cameroon","code":"237","iso":"CM","id":37},
    {"name":"Canada","code":"1","iso":"CA","id":38},
    {"name":"Cape Verde","code":"238","iso":"CV","id":39},
    {"name":"Cayman Islands","code":"1-345","iso":"KY","id":40},
    {"name":"Central African Republic","code":"236","iso":"CF","id":41},
    {"name":"Chad","code":"235","iso":"TD","id":42},
    {"name":"Chile","code":"56","iso":"CL","id":43},
    {"name":"China","code":"86","iso":"CN","id":44},
    {"name":"Christmas Island","code":"61","iso":"CX","id":45},
    {"name":"Cocos Islands","code":"61","iso":"CC","id":46},
    {"name":"Colombia","code":"57","iso":"CO","id":47},
    {"name":"Comoros","code":"269","iso":"KM","id":48},
    {"name":"Cook Islands","code":"682","iso":"CK","id":49},
    {"name":"Costa Rica","code":"506","iso":"CR","id":50},
    {"name":"Croatia","code":"385","iso":"HR","id":51},
    {"name":"Cuba","code":"53","iso":"CU","id":52},
    {"name":"Curacao","code":"599","iso":"CW","id":53},
    {"name":"Cyprus","code":"357","iso":"CY","id":54},
    {"name":"Czech Republic","code":"420","iso":"CZ","id":55},
    {"name":"Democratic Republic of the Congo","code":"243","iso":"CD","id":56},
    {"name":"Denmark","code":"45","iso":"DK","id":57},
    {"name":"Djibouti","code":"253","iso":"DJ","id":58},
    {"name":"Dominica","code":"1-767","iso":"DM","id":59},
    {"name":"Dominican Republic","code":"1-809, 1-829, 1-849","iso":"DO","id":60},
    {"name":"East Timor","code":"670","iso":"TL","id":61},
    {"name":"Ecuador","code":"593","iso":"EC","id":62},
    {"name":"Egypt","code":"20","iso":"EG","id":63},
    {"name":"El Salvador","code":"503","iso":"SV","id":64},
    {"name":"Equatorial Guinea","code":"240","iso":"GQ","id":65},
    {"name":"Eritrea","code":"291","iso":"ER","id":66},
    {"name":"Estonia","code":"372","iso":"EE","id":67},
    {"name":"Ethiopia","code":"251","iso":"ET","id":68},
    {"name":"Falkland Islands","code":"500","iso":"FK","id":69},
    {"name":"Faroe Islands","code":"298","iso":"FO","id":70},
    {"name":"Fiji","code":"679","iso":"FJ","id":71},
    {"name":"Finland","code":"358","iso":"FI","id":72},
    {"name":"France","code":"33","iso":"FR","id":73},
    {"name":"French Polynesia","code":"689","iso":"PF","id":74},
    {"name":"Gabon","code":"241","iso":"GA","id":75},
    {"name":"Gambia","code":"220","iso":"GM","id":76},
    {"name":"Georgia","code":"995","iso":"GE","id":77},
    {"name":"Germany","code":"49","iso":"DE","id":78},
    {"name":"Ghana","code":"233","iso":"GH","id":79},
    {"name":"Gibraltar","code":"350","iso":"GI","id":80},
    {"name":"Greece","code":"30","iso":"GR","id":81},
    {"name":"Greenland","code":"299","iso":"GL","id":82},
    {"name":"Grenada","code":"1-473","iso":"GD","id":83},
    {"name":"Guam","code":"1-671","iso":"GU","id":84},
    {"name":"Guatemala","code":"502","iso":"GT","id":85},
    {"name":"Guernsey","code":"44-1481","iso":"GG","id":86},
    {"name":"Guinea","code":"224","iso":"GN","id":87},
    {"name":"Guinea-Bissau","code":"245","iso":"GW","id":88},
    {"name":"Guyana","code":"592","iso":"GY","id":89},
    {"name":"Haiti","code":"509","iso":"HT","id":90},
    {"name":"Honduras","code":"504","iso":"HN","id":91},
    {"name":"Hong Kong","code":"852","iso":"HK","id":92},
    {"name":"Hungary","code":"36","iso":"HU","id":93},
    {"name":"Iceland","code":"354","iso":"IS","id":94},
    {"name":"India","code":"91","iso":"IN","id":95},
    {"name":"Indonesia","code":"62","iso":"ID","id":96},
    {"name":"Iran","code":"98","iso":"IR","id":97},
    {"name":"Iraq","code":"964","iso":"IQ","id":98},
    {"name":"Ireland","code":"353","iso":"IE","id":99},
    {"name":"Isle of Man","code":"44-1624","iso":"IM","id":100},
    {"name":"Israel","code":"972","iso":"IL","id":101},
    {"name":"Italy","code":"39","iso":"IT","id":102},
    {"name":"Ivory Coast","code":"225","iso":"CI","id":103},
    {"name":"Jamaica","code":"1-876","iso":"JM","id":104},
    {"name":"Japan","code":"81","iso":"JP","id":105},
    {"name":"Jersey","code":"44-1534","iso":"JE","id":106},
    {"name":"Jordan","code":"962","iso":"JO","id":107},
    {"name":"Kazakhstan","code":"7","iso":"KZ","id":108},
    {"name":"Kenya","code":"254","iso":"KE","id":109},
    {"name":"Kiribati","code":"686","iso":"KI","id":110},
    {"name":"Kosovo","code":"383","iso":"XK","id":111},
    {"name":"Kuwait","code":"965","iso":"KW","id":112},
    {"name":"Kyrgyzstan","code":"996","iso":"KG","id":113},
    {"name":"Laos","code":"856","iso":"LA","id":114},
    {"name":"Latvia","code":"371","iso":"LV","id":115},
    {"name":"Lebanon","code":"961","iso":"LB","id":116},
    {"name":"Lesotho","code":"266","iso":"LS","id":117},
    {"name":"Liberia","code":"231","iso":"LR","id":118},
    {"name":"Libya","code":"218","iso":"LY","id":119},
    {"name":"Liechtenstein","code":"423","iso":"LI","id":120},
    {"name":"Lithuania","code":"370","iso":"LT","id":121},
    {"name":"Luxembourg","code":"352","iso":"LU","id":122},
    {"name":"Macao","code":"853","iso":"MO","id":123},
    {"name":"Macedonia","code":"389","iso":"MK","id":124},
    {"name":"Madagascar","code":"261","iso":"MG","id":125},
    {"name":"Malawi","code":"265","iso":"MW","id":126},
    {"name":"Malaysia","code":"60","iso":"MY","id":127},
    {"name":"Maldives","code":"960","iso":"MV","id":128},
    {"name":"Mali","code":"223","iso":"ML","id":129},
    {"name":"Malta","code":"356","iso":"MT","id":130},
    {"name":"Marshall Islands","code":"692","iso":"MH","id":131},
    {"name":"Mauritania","code":"222","iso":"MR","id":132},
    {"name":"Mauritius","code":"230","iso":"MU","id":133},
    {"name":"Mayotte","code":"262","iso":"YT","id":134},
    {"name":"Mexico","code":"52","iso":"MX","id":135},
    {"name":"Micronesia","code":"691","iso":"FM","id":136},
    {"name":"Moldova","code":"373","iso":"MD","id":137},
    {"name":"Monaco","code":"377","iso":"MC","id":138},
    {"name":"Mongolia","code":"976","iso":"MN","id":139},
    {"name":"Montenegro","code":"382","iso":"ME","id":140},
    {"name":"Montserrat","code":"1-664","iso":"MS","id":141},
    {"name":"Morocco","code":"212","iso":"MA","id":142},
    {"name":"Mozambique","code":"258","iso":"MZ","id":143},
    {"name":"Myanmar","code":"95","iso":"MM","id":144},
    {"name":"Namibia","code":"264","iso":"NA","id":145},
    {"name":"Nauru","code":"674","iso":"NR","id":146},
    {"name":"Nepal","code":"977","iso":"NP","id":147},
    {"name":"Netherlands","code":"31","iso":"NL","id":148},
    {"name":"Netherlands Antilles","code":"599","iso":"AN","id":149},
    {"name":"New Caledonia","code":"687","iso":"NC","id":150},
    {"name":"New Zealand","code":"64","iso":"NZ","id":151},
    {"name":"Nicaragua","code":"505","iso":"NI","id":152},
    {"name":"Niger","code":"227","iso":"NE","id":153},
    {"name":"Nigeria","code":"234","iso":"NG","id":154},
    {"name":"Niue","code":"683","iso":"NU","id":155},
    {"name":"North Korea","code":"850","iso":"KP","id":156},
    {"name":"Northern Mariana Islands","code":"1-670","iso":"MP","id":157},
    {"name":"Norway","code":"47","iso":"NO","id":158},
    {"name":"Oman","code":"968","iso":"OM","id":159},
    {"name":"Pakistan","code":"92","iso":"PK","id":160},
    {"name":"Palau","code":"680","iso":"PW","id":161},
    {"name":"Palestine","code":"970","iso":"PS","id":162},
    {"name":"Panama","code":"507","iso":"PA","id":163},
    {"name":"Papua New Guinea","code":"675","iso":"PG","id":164},
    {"name":"Paraguay","code":"595","iso":"PY","id":165},
    {"name":"Peru","code":"51","iso":"PE","id":166},
    {"name":"Philippines","code":"63","iso":"PH","id":167},
    {"name":"Pitcairn","code":"64","iso":"PN","id":168},
    {"name":"Poland","code":"48","iso":"PL","id":169},
    {"name":"Portugal","code":"351","iso":"PT","id":170},
    {"name":"Puerto Rico","code":"1-787, 1-939","iso":"PR","id":171},
    {"name":"Qatar","code":"974","iso":"QA","id":172},
    {"name":"Republic of the Congo","code":"242","iso":"CG","id":173},
    {"name":"Reunion","code":"262","iso":"RE","id":174},
    {"name":"Romania","code":"40","iso":"RO","id":175},
    {"name":"Russia","code":"7","iso":"RU","id":176},
    {"name":"Rwanda","code":"250","iso":"RW","id":177},
    {"name":"Saint Barthelemy","code":"590","iso":"BL","id":178},
    {"name":"Saint Helena","code":"290","iso":"SH","id":179},
    {"name":"Saint Kitts and Nevis","code":"1-869","iso":"KN","id":180},
    {"name":"Saint Lucia","code":"1-758","iso":"LC","id":181},
    {"name":"Saint Martin","code":"590","iso":"MF","id":182},
    {"name":"Saint Pierre and Miquelon","code":"508","iso":"PM","id":183},
    {"name":"Saint Vincent and the Grenadines","code":"1-784","iso":"VC","id":184},
    {"name":"Samoa","code":"685","iso":"WS","id":185},
    {"name":"San Marino","code":"378","iso":"SM","id":186},
    {"name":"Sao Tome and Principe","code":"239","iso":"ST","id":187},
    {"name":"Saudi Arabia","code":"966","iso":"SA","id":188},
    {"name":"Senegal","code":"221","iso":"SN","id":189},
    {"name":"Serbia","code":"381","iso":"RS","id":190},
    {"name":"Seychelles","code":"248","iso":"SC","id":191},
    {"name":"Sierra Leone","code":"232","iso":"SL","id":192},
    {"name":"Singapore","code":"65","iso":"SG","id":193},
    {"name":"Sint Maarten","code":"1-721","iso":"SX","id":194},
    {"name":"Slovakia","code":"421","iso":"SK","id":195},
    {"name":"Slovenia","code":"386","iso":"SI","id":196},
    {"name":"Solomon Islands","code":"677","iso":"SB","id":197},
    {"name":"Somalia","code":"252","iso":"SO","id":198},
    {"name":"South Africa","code":"27","iso":"ZA","id":199},
    {"name":"South Korea","code":"82","iso":"KR","id":200},
    {"name":"South Sudan","code":"211","iso":"SS","id":201},
    {"name":"Spain","code":"34","iso":"ES","id":202},
    {"name":"Sri Lanka","code":"94","iso":"LK","id":203},
    {"name":"Sudan","code":"249","iso":"SD","id":204},
    {"name":"Suriname","code":"597","iso":"SR","id":205},
    {"name":"Svalbard and Jan Mayen","code":"47","iso":"SJ","id":206},
    {"name":"Swaziland","code":"268","iso":"SZ","id":207},
    {"name":"Sweden","code":"46","iso":"SE","id":208},
    {"name":"Switzerland","code":"41","iso":"CH","id":209},
    {"name":"Syria","code":"963","iso":"SY","id":210},
    {"name":"Taiwan","code":"886","iso":"TW","id":211},
    {"name":"Tajikistan","code":"992","iso":"TJ","id":212},
    {"name":"Tanzania","code":"255","iso":"TZ","id":213},
    {"name":"Thailand","code":"66","iso":"TH","id":214},
    {"name":"Togo","code":"228","iso":"TG","id":215},
    {"name":"Tokelau","code":"690","iso":"TK","id":216},
    {"name":"Tonga","code":"676","iso":"TO","id":217},
    {"name":"Trinidad and Tobago","code":"1-868","iso":"TT","id":218},
    {"name":"Tunisia","code":"216","iso":"TN","id":219},
    {"name":"Turkey","code":"90","iso":"TR","id":220},
    {"name":"Turkmenistan","code":"993","iso":"TM","id":221},
    {"name":"Turks and Caicos Islands","code":"1-649","iso":"TC","id":222},
    {"name":"Tuvalu","code":"688","iso":"TV","id":223},
    {"name":"U.S. Virgin Islands","code":"1-340","iso":"VI","id":224},
    {"name":"Uganda","code":"256","iso":"UG","id":225},
    {"name":"Ukraine","code":"380","iso":"UA","id":226},
    {"name":"United Arab Emirates","code":"971","iso":"AE","id":227},
    {"name":"United Kingdom","code":"44","iso":"GB","id":228},
    {"name":"United States","code":"1","iso":"US","id":229},
    {"name":"Uruguay","code":"598","iso":"UY","id":230},
    {"name":"Uzbekistan","code":"998","iso":"UZ","id":231},
    {"name":"Vanuatu","code":"678","iso":"VU","id":232},
    {"name":"Vatican","code":"379","iso":"VA","id":233},
    {"name":"Venezuela","code":"58","iso":"VE","id":234},
    {"name":"Vietnam","code":"84","iso":"VN","id":235},
    {"name":"Wallis and Futuna","code":"681","iso":"WF","id":236},
    {"name":"Western Sahara","code":"212","iso":"EH","id":237},
    {"name":"Yemen","code":"967","iso":"YE","id":238},
    {"name":"Zambia","code":"260","iso":"ZM","id":239},
    {"name":"Zimbabwe","code":"263","iso":"ZW","id":240}
    ]



  constructor() { }
}
